trigger:
  - develop

pr:
  branches:
    exclude:
      - '*'

resources:
  - repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: MavenAuthenticate@0
    inputs:
      mavenServiceConnections: 'blindnet-maven-snapshots'
  - task: Maven@3
    displayName: 'Deploy parent'
    inputs:
      goals: 'deploy'
      options: '-N'
  - task: Maven@3
    displayName: 'Deploy core'
    inputs:
      mavenPomFile: 'core/pom.xml'
      goals: 'javadoc:jar source:jar deploy'
